'use client'

import { useState, useEffect, Suspense } from 'react'
import { useRouter, useSearchParams } from 'next/navigation'
import { useSupabase } from '@/components/providers/supabase-provider'
import { Button } from '@/components/ui/Button'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/Card'
import { motion, AnimatePresence } from 'framer-motion'
import { HelpCircle, Target, Calendar, ArrowRight, ArrowLeft } from 'lucide-react'

function OnboardingContent() {
  const router = useRouter()
  const searchParams = useSearchParams()
  const { user } = useSupabase()
  const [goal, setGoal] = useState('')
  const [goalFromHomepage, setGoalFromHomepage] = useState(false)
  const [startDate, setStartDate] = useState(new Date().toISOString().split('T')[0])
  const [isGenerating, setIsGenerating] = useState(false)
  const [clarificationQuestions, setClarificationQuestions] = useState<string[]>([])
  const [showClarifications, setShowClarifications] = useState(false)
  const [clarificationAnswers, setClarificationAnswers] = useState<Record<string, string>>({})
  const [errorMessage, setErrorMessage] = useState<string | null>(null)
  const [currentQuestionIndex, setCurrentQuestionIndex] = useState(0)
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false)

  // Check if goal was passed from homepage (URL or localStorage)
  useEffect(() => {
    const goalFromUrl = searchParams.get('goal')
    if (goalFromUrl) {
      setGoal(decodeURIComponent(goalFromUrl))
      setGoalFromHomepage(true)
      return
    }

    const pendingGoal = localStorage.getItem('pendingGoal')
    if (pendingGoal) {
      setGoal(pendingGoal)
      setGoalFromHomepage(true)
      localStorage.removeItem('pendingGoal')
    }
  }, [searchParams])

  // Auto-generate plan when user is authenticated and goal is set (from homepage)
  useEffect(() => {
    if (user && goal.trim() && !isGenerating && !hasAutoGenerated && goalFromHomepage) {
      const timer = setTimeout(() => {
        setHasAutoGenerated(true)
        handleGeneratePlan()
      }, 1000)
      return () => clearTimeout(timer)
    }
  }, [user, goal, isGenerating, hasAutoGenerated, goalFromHomepage])

  if (!user) {
    return (
      <div className="min-h-screen bg-[#0a0a0a] flex items-center justify-center">
        <div className="text-center">
          <p className="text-[#d7d2cb]">Please log in to continue</p>
          <button
            onClick={() => router.push('/login')}
            className="mt-4 px-4 py-2 bg-[var(--primary)] text-white rounded-md hover:bg-[var(--primary)]/90"
          >
            Go to Login
          </button>
        </div>
      </div>
    )
  }

  const handleGeneratePlan = async () => {
    if (!goal.trim() || !startDate) {
      setErrorMessage('Please fill in all fields before generating your roadmap.')
      return
    }

    setIsGenerating(true)
    setErrorMessage(null)

    try {
      const clarifyResponse = await fetch('/api/clarify', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          goal: goal.trim(),
        }),
      })

      const clarifyData = await clarifyResponse.json()

      if (!clarifyResponse.ok) {
        const message =
          clarifyData?.message ||
          clarifyData?.error ||
          'Failed to analyze goal.'
        setErrorMessage(message)
        return
      }

      if (clarifyData.needsClarification && clarifyData.questions.length > 0) {
        setClarificationQuestions(clarifyData.questions)
        setCurrentQuestionIndex(0)
        setClarificationAnswers({})
        setShowClarifications(true)
        setIsGenerating(false)
        return
      }

      await generatePlan({})
    } catch (error) {
      console.error('Error analyzing goal:', error)
      setErrorMessage(
        error instanceof Error
          ? error.message
          : 'Failed to analyze your goal. Please try again.'
      )
    } finally {
      setIsGenerating(false)
    }
  }

  const generatePlan = async (clarifications: Record<string, string>) => {
    setIsGenerating(true)
    setErrorMessage(null)

    try {
      const response = await fetch('/api/plans/generate', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          goal_text: goal.trim(),
          start_date: startDate,
          clarifications: Object.keys(clarifications).length > 0 ? clarifications : undefined,
          clarification_questions: clarificationQuestions.length > 0 ? clarificationQuestions : undefined,
        }),
      })

      const data = await response.json()

      if (!response.ok) {
        const message =
          data?.message ||
          data?.error ||
          'Failed to generate plan.'
        setErrorMessage(message)
        return
      }

      if (data.success && data.plan?.id) {
        sessionStorage.setItem('generatedPlan', JSON.stringify({
          plan: data.plan,
          tasks: data.tasks || [],
        }))
        router.push('/onboarding/review')
      } else {
        throw new Error('Plan creation failed - no plan ID returned')
      }
    } catch (error) {
      console.error('Error generating plan:', error)
      setErrorMessage(
        error instanceof Error ? error.message : 'Failed to generate plan. Please try again.'
      )
    } finally {
      setIsGenerating(false)
    }
  }

  const handleClarificationAnswer = (answer: string) => {
    const newAnswers = {
      ...clarificationAnswers,
      [currentQuestionIndex.toString()]: answer,
    }
    setClarificationAnswers(newAnswers)

    if (currentQuestionIndex < clarificationQuestions.length - 1) {
      setCurrentQuestionIndex(currentQuestionIndex + 1)
    } else {
      const formattedAnswers: Record<string, string> = {}
      clarificationQuestions.forEach((_, index) => {
        formattedAnswers[`clarification_${index + 1}`] = newAnswers[index.toString()] || ''
      })
      setShowClarifications(false)
      generatePlan(formattedAnswers)
    }
  }

  const handleClarificationSkip = () => {
    setShowClarifications(false)
    generatePlan({})
  }

  const handleClarificationBack = () => {
    if (currentQuestionIndex > 0) {
      setCurrentQuestionIndex(currentQuestionIndex - 1)
    } else {
      setShowClarifications(false)
    }
  }

  return (
    <div className="min-h-screen bg-[#0a0a0a] flex items-center justify-center py-12 px-4">
      <div className="w-full max-w-2xl">
        <AnimatePresence mode="wait">
          {!showClarifications ? (
            <motion.div
              key="goal-input"
              initial={{ opacity: 1 }}
              exit={{ opacity: 0, x: -20 }}
              transition={{ duration: 0.3, ease: 'easeInOut' }}
            >
              <div className="text-center mb-8">
                <h1 className="text-4xl font-bold text-[#d7d2cb] mb-4">
                  Let's Create Your Roadmap
                </h1>
                <p className="text-xl text-[#d7d2cb]/70">
                  Tell us your goal and we'll generate a personalized action plan
                </p>
              </div>

              <Card className="bg-white/5 border-white/10 relative overflow-hidden">
                <CardHeader>
                  {errorMessage && (
                    <div className="mb-4 rounded-lg border border-red-500/40 bg-red-500/10 px-4 py-3 text-left text-sm text-red-200">
                      {errorMessage}
                    </div>
                  )}
                  <div className="flex items-center gap-4 mb-2">
                    <div className="w-12 h-12 rounded-full bg-[#ff7f00]/20 flex items-center justify-center">
                      <Target className="w-6 h-6 text-[#ff7f00]" />
                    </div>
                    <div>
                      <CardTitle className="text-2xl text-[#d7d2cb]">
                        Describe Your Goal
                      </CardTitle>
                      <CardDescription className="text-[#d7d2cb]/70 mt-1">
                        What do you want to achieve?
                      </CardDescription>
                    </div>
                  </div>
                </CardHeader>
                <CardContent className="space-y-6">
                  <div>
                    <textarea
                      id="goal"
                      value={goal}
                      onChange={(e) => setGoal(e.target.value)}
                      placeholder="e.g., Learn to play guitar, Start a blog, Get in shape..."
                      className="w-full px-4 py-4 text-lg bg-white/5 border border-white/10 rounded-xl text-[#d7d2cb] placeholder-[#d7d2cb]/40 focus:outline-none focus:border-[#ff7f00] focus:ring-2 focus:ring-[#ff7f00]/20 transition-all resize-none"
                      rows={4}
                    />
                  </div>

                  <div>
                    <div className="flex items-center gap-2 mb-3">
                      <Calendar className="w-4 h-4 text-[#d7d2cb]/70" />
                      <label htmlFor="startDate" className="text-sm font-medium text-[#d7d2cb]/70">
                        Start Date
                      </label>
                    </div>
                    <input
                      type="date"
                      id="startDate"
                      value={startDate}
                      onChange={(e) => setStartDate(e.target.value)}
                      className="w-full px-4 py-4 text-lg bg-white/5 border border-white/10 rounded-xl text-[#d7d2cb] focus:outline-none focus:border-[#ff7f00] focus:ring-2 focus:ring-[#ff7f00]/20 transition-all"
                    />
                  </div>

                  <div className="pt-6 border-t border-white/10">
                    <Button
                      onClick={handleGeneratePlan}
                      disabled={!goal.trim() || !startDate || isGenerating}
                      className="w-full flex items-center justify-center gap-2"
                      variant="primary"
                      size="lg"
                    >
                      {isGenerating ? (
                        'Generating Your Plan...'
                      ) : (
                        <>
                          Generate My Roadmap
                          <ArrowRight className="w-4 h-4" />
                        </>
                      )}
                    </Button>
                  </div>
                </CardContent>
              </Card>

              <div className="mt-6 flex justify-center">
                <Button
                  onClick={() => router.push('/dashboard')}
                  variant="outline"
                  size="sm"
                  className="flex items-center gap-2"
                >
                  <ArrowLeft className="w-4 h-4" />
                  Return to Dashboard
                </Button>
              </div>
            </motion.div>
          ) : (
            <motion.div
              key="clarifications"
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -20 }}
              transition={{ duration: 0.3, ease: 'easeInOut' }}
            >
              <div className="mb-8">
                <div className="flex items-center justify-between mb-2">
                  <span className="text-sm text-[#d7d2cb]/70">
                    Question {currentQuestionIndex + 1} of {clarificationQuestions.length}
                  </span>
                  <span className="text-sm text-[#d7d2cb]/70">
                    {Math.round(((currentQuestionIndex + 1) / clarificationQuestions.length) * 100)}%
                  </span>
                </div>
                <div className="w-full h-2 bg-white/5 rounded-full overflow-hidden">
                  <motion.div
                    className="h-full bg-[#ff7f00] rounded-full"
                    initial={{ width: 0 }}
                    animate={{ width: `${((currentQuestionIndex + 1) / clarificationQuestions.length) * 100}%` }}
                    transition={{ duration: 0.3 }}
                  />
                </div>
              </div>

              <Card className="bg-white/5 border-white/10 relative overflow-hidden">
                <CardHeader>
                  <div className="flex items-center gap-4 mb-2">
                    <div className="w-12 h-12 rounded-full bg-[#ff7f00]/20 flex items-center justify-center">
                      <HelpCircle className="w-6 h-6 text-[#ff7f00]" />
                    </div>
                    <div>
                      <CardTitle className="text-2xl text-[#d7d2cb]">
                        Help Us Understand Your Goal
                      </CardTitle>
                      <CardDescription className="text-[#d7d2cb]/70 mt-1">
                        <AnimatePresence mode="wait">
                          <motion.span
                            key={currentQuestionIndex}
                            initial={{ opacity: 0, y: 5 }}
                            animate={{ opacity: 1, y: 0 }}
                            exit={{ opacity: 0, y: -5 }}
                            transition={{ duration: 0.2 }}
                          >
                            {clarificationQuestions[currentQuestionIndex]}
                          </motion.span>
                        </AnimatePresence>
                      </CardDescription>
                    </div>
                  </div>
                </CardHeader>
                <CardContent className="space-y-6">
                  <motion.div
                    key={`answer-${currentQuestionIndex}`}
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.3 }}
                  >
                    <textarea
                      id="clarification-answer"
                      value={clarificationAnswers[currentQuestionIndex.toString()] || ''}
                      onChange={(e) => {
                        const newAnswers = {
                          ...clarificationAnswers,
                          [currentQuestionIndex.toString()]: e.target.value,
                        }
                        setClarificationAnswers(newAnswers)
                      }}
                      placeholder="Type your answer here..."
                      className="w-full px-4 py-4 text-lg bg-white/5 border border-white/10 rounded-xl text-[#d7d2cb] placeholder-[#d7d2cb]/40 focus:outline-none focus:border-[#ff7f00] focus:ring-2 focus:ring-[#ff7f00]/20 transition-all resize-none"
                      rows={4}
                      autoFocus
                    />
                  </motion.div>

                  <div className="flex items-center justify-between pt-6 border-t border-white/10">
                    <Button
                      type="button"
                      variant="outline"
                      onClick={handleClarificationBack}
                      disabled={isGenerating}
                      className="flex items-center gap-2"
                    >
                      <ArrowLeft className="w-4 h-4" />
                      {currentQuestionIndex === 0 ? 'Back' : 'Previous'}
                    </Button>

                    <div className="flex gap-2">
                      <Button
                        type="button"
                        variant="ghost"
                        onClick={handleClarificationSkip}
                        disabled={isGenerating}
                        className="text-[#d7d2cb]/60 hover:text-[#d7d2cb]"
                      >
                        Skip All
                      </Button>

                      <Button
                        type="button"
                        variant="primary"
                        onClick={() => {
                          const answer = clarificationAnswers[currentQuestionIndex.toString()] || ''
                          if (answer.trim()) {
                            handleClarificationAnswer(answer)
                          }
                        }}
                        disabled={
                          isGenerating || !clarificationAnswers[currentQuestionIndex.toString()]?.trim()
                        }
                        className="flex items-center gap-2"
                      >
                        {isGenerating ? (
                          'Processing...'
                        ) : currentQuestionIndex === clarificationQuestions.length - 1 ? (
                          <>
                            Create Plan
                            <ArrowRight className="w-4 h-4" />
                          </>
                        ) : (
                          <>
                            Next
                            <ArrowRight className="w-4 h-4" />
                          </>
                        )}
                      </Button>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  )
}

export default function OnboardingPage() {
  return (
    <Suspense fallback={
      <div className="min-h-screen bg-[#0a0a0a] flex items-center justify-center">
        <div className="w-8 h-8 border-4 border-[#ff7f00] border-t-transparent rounded-full animate-spin" />
      </div>
    }>
      <OnboardingContent />
    </Suspense>
  )
}