'use client'

import { useState, useEffect, useRef, Suspense } from 'react'
import { useRouter, useSearchParams } from 'next/navigation'
import { useSupabase } from '@/components/providers/supabase-provider'
import { Button } from '@/components/ui/Button'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/Card'
import { motion, AnimatePresence } from 'framer-motion'
import { Target, Calendar, ArrowRight, ArrowLeft, Loader2 } from 'lucide-react'

function OnboardingContent() {
  const router = useRouter()
  const searchParams = useSearchParams()
  const { user } = useSupabase()
  const [goal, setGoal] = useState('')
  const [goalFromHomepage, setGoalFromHomepage] = useState(false)
  const [startDate, setStartDate] = useState(new Date().toISOString().split('T')[0])
  const [isGenerating, setIsGenerating] = useState(false)
  const [errorMessage, setErrorMessage] = useState<string | null>(null)
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false)
  const hasFetchedWaitlistGoal = useRef(false)

  /**
   * Goal Priority System:
   * 
   * Priority 1: URL parameter (from homepage GoalInput)
   *   - User explicitly enters a goal on homepage and signs up
   *   - Takes precedence over waitlist goal (user's explicit choice)
   * 
   * Priority 2: localStorage/sessionStorage (from homepage GoalInput)
   *   - Fallback if URL parameter not available
   *   - Also takes precedence over waitlist goal
   * 
   * Priority 3: Waitlist goal retrieval
   *   - Only used if no goal from homepage (Priorities 1 & 2)
   *   - For users who signed up to waitlist but didn't enter a new goal on homepage
   * 
   * Rationale: If a user explicitly enters a new goal on the homepage, it should
   * override their old waitlist goal, as it represents their current intent.
   */
  
  // Priority 1 & 2: Check URL parameter and localStorage/sessionStorage (from homepage)
  useEffect(() => {
    // Priority 1: URL parameter (from homepage GoalInput or signup redirect)
    const goalFromUrl = searchParams.get('goal')
    if (goalFromUrl) {
      setGoal(decodeURIComponent(goalFromUrl))
      setGoalFromHomepage(true)
      hasFetchedWaitlistGoal.current = true // Prevent waitlist fetch if goal from URL
      return
    }

    // Priority 2: localStorage/sessionStorage (from homepage GoalInput)
    const pendingGoal = localStorage.getItem('pendingGoal') || sessionStorage.getItem('pendingGoal')
    if (pendingGoal) {
      setGoal(pendingGoal)
      setGoalFromHomepage(true)
      localStorage.removeItem('pendingGoal')
      sessionStorage.removeItem('pendingGoal')
      hasFetchedWaitlistGoal.current = true // Prevent waitlist fetch if goal from storage
      return
    }
  }, [searchParams])

  // Priority 3: Waitlist goal retrieval (for users who were on waitlist)
  // Separate effect that only depends on user.email to ensure it runs when user becomes available
  useEffect(() => {
    // Only fetch if:
    // 1. User is authenticated
    // 2. Goal is currently empty (no goal from homepage)
    // 3. We haven't already fetched (to prevent duplicate calls)
    if (user?.email && !goal.trim() && !hasFetchedWaitlistGoal.current) {
      hasFetchedWaitlistGoal.current = true // Mark as fetched to prevent duplicate calls
      
      const fetchWaitlistGoal = async () => {
        try {
          console.log('[Onboarding] Fetching waitlist goal for email:', user.email)
          const response = await fetch('/api/waitlist/retrieve-goal')
          if (response.ok) {
            const data = await response.json()
            console.log('[Onboarding] Waitlist goal response:', data)
            if (data.success && data.goal) {
              console.log('[Onboarding] Setting goal from waitlist:', data.goal)
              setGoal(data.goal)
              setGoalFromHomepage(true)
            } else {
              console.log('[Onboarding] No goal found in waitlist for this email')
            }
          } else {
            const errorData = await response.json().catch(() => ({}))
            console.error('[Onboarding] Failed to retrieve waitlist goal - response not ok:', response.status, errorData)
          }
        } catch (error) {
          // Silently fail - user can still enter goal manually
          console.error('[Onboarding] Failed to retrieve waitlist goal:', error)
        }
      }
      fetchWaitlistGoal()
    }
  }, [user?.email, goal])

  // Auto-generate plan when user is authenticated and goal is set (from homepage)
  useEffect(() => {
    if (user && goal.trim() && !isGenerating && !hasAutoGenerated && goalFromHomepage) {
      const timer = setTimeout(() => {
        setHasAutoGenerated(true)
        handleGeneratePlan()
      }, 1000)
      return () => clearTimeout(timer)
    }
  }, [goal, goalFromHomepage, hasAutoGenerated, isGenerating, user])


  if (!user) {
    return (
      <div className="min-h-screen bg-[#0a0a0a] flex items-center justify-center">
        <div className="text-center">
          <p className="text-[#d7d2cb]">Please log in to continue</p>
          <button
            onClick={() => router.push('/login')}
            className="mt-4 px-4 py-2 bg-[var(--primary)] text-white rounded-md hover:bg-[var(--primary)]/90"
          >
            Go to Login
          </button>
        </div>
      </div>
    )
  }

  const handleGeneratePlan = async () => {
    if (!goal.trim() || !startDate) {
      setErrorMessage('Please fill in all fields before generating your plan.')
      return
    }

    // Skip initial clarifications - go directly to plan generation
    await generatePlan({})
  }

  const generatePlan = async (clarifications: Record<string, string>) => {
    setIsGenerating(true)
    setErrorMessage(null)

    try {
      const response = await fetch('/api/plans/generate', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          goal_text: goal.trim(),
          start_date: startDate,
          clarifications: Object.keys(clarifications).length > 0 ? clarifications : undefined,
          timezone_offset: new Date().getTimezoneOffset(), // Send timezone offset in minutes
        }),
      })

      const data = await response.json()

      if (!response.ok) {
        // Check if this is a usage limit exceeded error
        if (data?.error === 'USAGE_LIMIT_EXCEEDED' || data?.message?.includes('USAGE_LIMIT_EXCEEDED') || data?.message?.includes("plan's limit")) {
          setErrorMessage("You've reached your plan's limit for this feature. Please upgrade your plan or wait for the next billing cycle.")
        } else {
          const message =
            data?.message ||
            data?.error ||
            'Failed to generate plan.'
          setErrorMessage(message)
        }
        return
      }

      if (data.success && data.plan?.id) {
        const tasksArray = Array.isArray(data.tasks) ? data.tasks : Array.isArray(data.tasks?.items) ? data.tasks.items : []
        sessionStorage.setItem('generatedPlan', JSON.stringify({
          plan: data.plan,
          tasks: tasksArray,
        }))
        router.push('/onboarding/review')
      } else {
        throw new Error('Plan creation failed - no plan ID returned')
      }
    } catch (error) {
      console.error('Error generating plan:', error)
      setErrorMessage(
        error instanceof Error ? error.message : 'Failed to generate plan. Please try again.'
      )
    } finally {
      setIsGenerating(false)
    }
  }


  return (
    <div className="min-h-screen bg-[#0a0a0a] flex items-center justify-center py-12 px-4">
      <div className="w-full max-w-2xl">
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.5, ease: 'easeOut' }}
        >
              <motion.div
                initial={{ opacity: 0, y: -20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: 0.1, ease: 'easeOut' }}
                className="text-center mb-8"
              >
                <h1 className="text-4xl font-bold text-[#d7d2cb] mb-4">
                  Let's Create Your Plan
                </h1>
                <p className="text-xl text-[#d7d2cb]/70">
                  Tell us your goal and we'll generate a personalized action plan
                </p>
              </motion.div>

              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: 0.2, ease: 'easeOut' }}
              >
                <Card className="bg-white/5 border-white/10 relative overflow-hidden">
                <CardHeader>
                  {errorMessage && (
                    <div className="mb-4 rounded-lg border border-red-500/40 bg-red-500/10 px-4 py-3 text-left">
                      {errorMessage.includes("plan's limit") ? (
                        <div className="flex flex-col gap-2">
                          <p className="text-sm font-medium text-red-200">
                            Feature limit reached
                          </p>
                          <p className="text-xs text-red-200/80">
                            {errorMessage}
                          </p>
                          <a
                            href="/pricing"
                            className="text-xs underline mt-1 text-red-200/80 hover:text-red-200 transition-colors"
                          >
                            View pricing plans →
                          </a>
                        </div>
                      ) : (
                        <p className="text-sm text-red-200">{errorMessage}</p>
                      )}
                    </div>
                  )}
                  <div className="flex items-center gap-4 mb-2">
                    <div className="w-12 h-12 rounded-full bg-[#ff7f00]/20 flex items-center justify-center">
                      <Target className="w-6 h-6 text-[#ff7f00]" />
                    </div>
                    <div>
                      <CardTitle className="text-2xl text-[#d7d2cb]">
                        Describe Your Goal
                      </CardTitle>
                      <CardDescription className="text-[#d7d2cb]/70 mt-1">
                        What do you want to achieve?
                      </CardDescription>
                    </div>
                  </div>
                </CardHeader>
                <CardContent className="space-y-6">
                  <div>
                    <textarea
                      id="goal"
                      value={goal}
                      onChange={(e) => setGoal(e.target.value)}
                      placeholder="e.g., Learn to play guitar, Start a blog, Get in shape..."
                      className="w-full px-4 py-4 text-lg bg-white/5 border border-white/10 rounded-xl text-[#d7d2cb] placeholder-[#d7d2cb]/40 focus:outline-none focus:border-[#ff7f00] focus:ring-2 focus:ring-[#ff7f00]/20 transition-all resize-none"
                      rows={4}
                    />
                  </div>

                  <div>
                    <div className="flex items-center gap-2 mb-3">
                      <Calendar className="w-4 h-4 text-[#d7d2cb]/70" />
                      <label htmlFor="startDate" className="text-sm font-medium text-[#d7d2cb]/70">
                        Start Date
                      </label>
                    </div>
                    <input
                      type="date"
                      id="startDate"
                      value={startDate}
                      onChange={(e) => setStartDate(e.target.value)}
                      className="w-full px-4 py-4 text-lg bg-white/5 border border-white/10 rounded-xl text-[#d7d2cb] focus:outline-none focus:border-[#ff7f00] focus:ring-2 focus:ring-[#ff7f00]/20 transition-all"
                    />
                  </div>

                  <div className="pt-6 border-t border-white/10">
                    <Button
                      onClick={handleGeneratePlan}
                      disabled={!goal.trim() || !startDate || isGenerating}
                      className="w-full flex items-center justify-center gap-2"
                      variant="primary"
                      size="lg"
                    >
                      {isGenerating ? (
                        <Loader2 className="w-5 h-5 animate-spin" />
                      ) : (
                        <>
                          Generate My Plan
                          <ArrowRight className="w-4 h-4" />
                        </>
                      )}
                    </Button>
                  </div>
                </CardContent>
              </Card>
              </motion.div>

              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ duration: 0.4, delay: 0.4, ease: 'easeOut' }}
                className="mt-6 flex justify-center"
              >
                <Button
                  onClick={() => router.push('/dashboard')}
                  variant="outline"
                  size="sm"
                  className="flex items-center gap-2"
                >
                  <ArrowLeft className="w-4 h-4" />
                  Return to Dashboard
                </Button>
              </motion.div>
            </motion.div>
      </div>
    </div>
  )
}

export default function OnboardingPage() {
  return (
    <Suspense fallback={
      <div className="min-h-screen bg-[#0a0a0a] flex items-center justify-center">
        <div className="w-8 h-8 border-4 border-[#ff7f00] border-t-transparent rounded-full animate-spin" />
      </div>
    }>
      <OnboardingContent />
    </Suspense>
  )
}