'use client'

import { useState, useEffect, Suspense } from 'react'
import { useRouter, useSearchParams } from 'next/navigation'
import { useSupabase } from '@/components/providers/supabase-provider'
import { Button } from '@/components/ui/Button'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/Card'
import { motion, AnimatePresence } from 'framer-motion'
import { Target, Calendar, ArrowRight, ArrowLeft } from 'lucide-react'
import { useUsageSummary } from '@/hooks/useUsageSummary'

function OnboardingContent() {
  const router = useRouter()
  const searchParams = useSearchParams()
  const { user } = useSupabase()
  const {
    getMetric: getUsageMetric,
    loading: loadingUsage,
    error: usageError,
    refresh: refreshUsage,
  } = useUsageSummary(user?.id)
  const [goal, setGoal] = useState('')
  const [goalFromHomepage, setGoalFromHomepage] = useState(false)
  const [startDate, setStartDate] = useState(new Date().toISOString().split('T')[0])
  const [isGenerating, setIsGenerating] = useState(false)
  const [errorMessage, setErrorMessage] = useState<string | null>(null)
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false)

  // Check if goal was passed from homepage (URL or localStorage)
  useEffect(() => {
    const goalFromUrl = searchParams.get('goal')
    if (goalFromUrl) {
      setGoal(decodeURIComponent(goalFromUrl))
      setGoalFromHomepage(true)
      return
    }

    const pendingGoal = localStorage.getItem('pendingGoal')
    if (pendingGoal) {
      setGoal(pendingGoal)
      setGoalFromHomepage(true)
      localStorage.removeItem('pendingGoal')
    }
  }, [searchParams])

  // Auto-generate plan when user is authenticated and goal is set (from homepage)
  useEffect(() => {
    if (user && goal.trim() && !isGenerating && !hasAutoGenerated && goalFromHomepage) {
      const timer = setTimeout(() => {
        setHasAutoGenerated(true)
        handleGeneratePlan()
      }, 1000)
      return () => clearTimeout(timer)
    }
  }, [goal, goalFromHomepage, hasAutoGenerated, isGenerating, user])

  useEffect(() => {
    if (user?.id) {
      refreshUsage()
    }
  }, [refreshUsage, user?.id])

  const aiCredits = getUsageMetric('api_credits')
  const creditsDepleted = aiCredits && aiCredits.available <= 0

  if (!user) {
    return (
      <div className="min-h-screen bg-[#0a0a0a] flex items-center justify-center">
        <div className="text-center">
          <p className="text-[#d7d2cb]">Please log in to continue</p>
          <button
            onClick={() => router.push('/login')}
            className="mt-4 px-4 py-2 bg-[var(--primary)] text-white rounded-md hover:bg-[var(--primary)]/90"
          >
            Go to Login
          </button>
        </div>
      </div>
    )
  }

  const handleGeneratePlan = async () => {
    if (!goal.trim() || !startDate) {
      setErrorMessage('Please fill in all fields before generating your roadmap.')
      return
    }

    // Skip initial clarifications - go directly to plan generation
    await generatePlan({})
  }

  const generatePlan = async (clarifications: Record<string, string>) => {
    setIsGenerating(true)
    setErrorMessage(null)

    try {
      const response = await fetch('/api/plans/generate', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          goal_text: goal.trim(),
          start_date: startDate,
          clarifications: Object.keys(clarifications).length > 0 ? clarifications : undefined,
          clarification_questions: clarificationQuestions.length > 0 ? clarificationQuestions : undefined,
          timezone_offset: new Date().getTimezoneOffset(), // Send timezone offset in minutes
        }),
      })

      const data = await response.json()

      if (!response.ok) {
        const message =
          data?.message ||
          data?.error ||
          'Failed to generate plan.'
        setErrorMessage(message)
        return
      }

      if (data.success && data.plan?.id) {
        const tasksArray = Array.isArray(data.tasks) ? data.tasks : Array.isArray(data.tasks?.items) ? data.tasks.items : []
        sessionStorage.setItem('generatedPlan', JSON.stringify({
          plan: data.plan,
          tasks: tasksArray,
        }))
        router.push('/onboarding/review')
      } else {
        throw new Error('Plan creation failed - no plan ID returned')
      }
    } catch (error) {
      console.error('Error generating plan:', error)
      setErrorMessage(
        error instanceof Error ? error.message : 'Failed to generate plan. Please try again.'
      )
    } finally {
      setIsGenerating(false)
    }
  }


  return (
    <div className="min-h-screen bg-[#0a0a0a] flex items-center justify-center py-12 px-4">
      <div className="w-full max-w-2xl">
        <motion.div
          initial={{ opacity: 1 }}
          transition={{ duration: 0.3, ease: 'easeInOut' }}
        >
              <div className="text-center mb-8">
                <h1 className="text-4xl font-bold text-[#d7d2cb] mb-4">
                  Let's Create Your Roadmap
                </h1>
                <p className="text-xl text-[#d7d2cb]/70">
                  Tell us your goal and we'll generate a personalized action plan
                </p>
              </div>

              <Card className="bg-white/5 border-white/10 relative overflow-hidden">
                <CardHeader>
                  {errorMessage && (
                    <div className="mb-4 rounded-lg border border-red-500/40 bg-red-500/10 px-4 py-3 text-left text-sm text-red-200">
                      {errorMessage}
                    </div>
                  )}
                  <div className="flex items-center gap-4 mb-2">
                    <div className="w-12 h-12 rounded-full bg-[#ff7f00]/20 flex items-center justify-center">
                      <Target className="w-6 h-6 text-[#ff7f00]" />
                    </div>
                    <div>
                      <CardTitle className="text-2xl text-[#d7d2cb]">
                        Describe Your Goal
                      </CardTitle>
                      <CardDescription className="text-[#d7d2cb]/70 mt-1">
                        What do you want to achieve?
                      </CardDescription>
                    </div>
                  </div>
                </CardHeader>
                <CardContent className="space-y-6">
                  <div>
                    <textarea
                      id="goal"
                      value={goal}
                      onChange={(e) => setGoal(e.target.value)}
                      placeholder="e.g., Learn to play guitar, Start a blog, Get in shape..."
                      className="w-full px-4 py-4 text-lg bg-white/5 border border-white/10 rounded-xl text-[#d7d2cb] placeholder-[#d7d2cb]/40 focus:outline-none focus:border-[#ff7f00] focus:ring-2 focus:ring-[#ff7f00]/20 transition-all resize-none"
                      rows={4}
                    />
                  </div>

                  <div>
                    <div className="flex items-center gap-2 mb-3">
                      <Calendar className="w-4 h-4 text-[#d7d2cb]/70" />
                      <label htmlFor="startDate" className="text-sm font-medium text-[#d7d2cb]/70">
                        Start Date
                      </label>
                    </div>
                    <input
                      type="date"
                      id="startDate"
                      value={startDate}
                      onChange={(e) => setStartDate(e.target.value)}
                      className="w-full px-4 py-4 text-lg bg-white/5 border border-white/10 rounded-xl text-[#d7d2cb] focus:outline-none focus:border-[#ff7f00] focus:ring-2 focus:ring-[#ff7f00]/20 transition-all"
                    />
                  </div>

                  <div className="pt-6 border-t border-white/10">
                    <Button
                      onClick={handleGeneratePlan}
                      disabled={!goal.trim() || !startDate || isGenerating}
                      className="w-full flex items-center justify-center gap-2"
                      variant="primary"
                      size="lg"
                    >
                      {isGenerating ? (
                        'Generating Your Plan...'
                      ) : (
                        <>
                          Generate My Roadmap
                          <ArrowRight className="w-4 h-4" />
                        </>
                      )}
                    </Button>
                  <div className="mt-3 text-center">
                    {loadingUsage ? (
                      <p className="text-sm text-[#d7d2cb]/60">Checking your available credits…</p>
                    ) : usageError ? (
                      <p className="text-sm text-red-300">Unable to load credit usage. Please try again.</p>
                    ) : aiCredits ? (
                      <p
                        className={`text-sm ${
                          creditsDepleted ? 'text-red-300 font-semibold' : 'text-[#d7d2cb]/70'
                        }`}
                      >
                        {creditsDepleted
                          ? 'No AI credits remaining this billing cycle.'
                          : `${aiCredits.available.toLocaleString()} of ${aiCredits.allocation.toLocaleString()} AI credits remaining this cycle.`}
                      </p>
                    ) : (
                      <p className="text-sm text-[#d7d2cb]/60">
                        Credit usage not available yet. Start generating to initialize your cycle.
                      </p>
                    )}
                  </div>
                  </div>
                </CardContent>
              </Card>

              <div className="mt-6 flex justify-center">
                <Button
                  onClick={() => router.push('/dashboard')}
                  variant="outline"
                  size="sm"
                  className="flex items-center gap-2"
                >
                  <ArrowLeft className="w-4 h-4" />
                  Return to Dashboard
                </Button>
              </div>
            </motion.div>
      </div>
    </div>
  )
}

export default function OnboardingPage() {
  return (
    <Suspense fallback={
      <div className="min-h-screen bg-[#0a0a0a] flex items-center justify-center">
        <div className="w-8 h-8 border-4 border-[#ff7f00] border-t-transparent rounded-full animate-spin" />
      </div>
    }>
      <OnboardingContent />
    </Suspense>
  )
}